tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "on-surface-variant": "var(--on-surface-variant)",
                "surface-container-highest": "var(--surface-container-highest)",
                "surface-container-lowest": "var(--surface-container-lowest)",
                "primary": "var(--primary)",
                "on-secondary-container": "var(--on-secondary-container)",
                "on-tertiary": "var(--on-tertiary)",
                "secondary-fixed": "var(--secondary-fixed)",
                "error-container": "var(--error-container)",
                "on-error": "var(--on-error)",
                "surface-tint": "var(--surface-tint)",
                "surface": "var(--surface)",
                "surface-dim": "var(--surface-dim)",
                "surface-container-high": "var(--surface-container-high)",
                "background": "var(--background)",
                "surface-bright": "var(--surface-bright)",
                "on-background": "var(--on-background)",
                "tertiary-fixed": "var(--tertiary-fixed)",
                "on-primary-container": "var(--on-primary-container)",
                "surface-variant": "var(--surface-variant)",
                "tertiary": "var(--tertiary)",
                "on-tertiary-fixed-variant": "var(--on-tertiary-fixed-variant)",
                "secondary-fixed-dim": "var(--secondary-fixed-dim)",
                "secondary-container": "var(--secondary-container)",
                "primary-container": "var(--primary-container)",
                "on-tertiary-fixed": "var(--on-tertiary-fixed)",
                "on-tertiary-container": "var(--on-tertiary-container)",
                "on-secondary": "var(--on-secondary)",
                "inverse-surface": "var(--inverse-surface)",
                "inverse-on-surface": "var(--inverse-on-surface)",
                "on-surface": "var(--on-surface)",
                "surface-container": "var(--surface-container)",
                "primary-fixed": "var(--primary-fixed)",
                "on-primary-fixed": "var(--on-primary-fixed)",
                "inverse-primary": "var(--inverse-primary)",
                "on-secondary-fixed-variant": "var(--on-secondary-fixed-variant)",
                "primary-fixed-dim": "var(--primary-fixed-dim)",
                "outline-variant": "var(--outline-variant)",
                "outline": "var(--outline)",
                "on-primary-fixed-variant": "var(--on-primary-fixed-variant)",
                "on-primary": "var(--on-primary)",
                "secondary": "var(--secondary)",
                "surface-container-low": "var(--surface-container-low)",
                "tertiary-container": "var(--tertiary-container)",
                "error": "var(--error)",
                "tertiary-fixed-dim": "var(--tertiary-fixed-dim)",
                "on-error-container": "var(--on-error-container)",
                "on-secondary-fixed": "var(--on-secondary-fixed)"
            },
            "borderRadius": {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px",
                "2xl": "1rem",
                "3xl": "1.5rem"
            },
            "spacing": {
                "gutter": "32px",
                "container-max": "1280px",
                "margin-mobile": "20px",
                "unit": "8px",
                "margin-desktop": "64px"
            },
            "fontFamily": {
                "headline-lg-mobile": ["Playfair Display"],
                "display-lg": ["Playfair Display"],
                "headline-md": ["Playfair Display"],
                "body-lg": ["Inter"],
                "body-md": ["Inter"],
                "label-md": ["Inter"],
                "headline-lg": ["Playfair Display"],
                "display-lg-mobile": ["Playfair Display"]
            },
            "fontSize": {
                "headline-lg-mobile": ["32px", { "lineHeight": "1.3", "fontWeight": "600" }],
                "display-lg": ["64px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
                "headline-md": ["28px", { "lineHeight": "1.4", "fontWeight": "500" }],
                "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
                "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
                "label-md": ["14px", { "lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600" }],
                "headline-lg": ["40px", { "lineHeight": "1.2", "fontWeight": "600" }],
                "display-lg-mobile": ["40px", { "lineHeight": "1.2", "fontWeight": "700" }]
            }
        }
    }
}
