services:
  - type: web
    name: luxestay-api
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: luxestay-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        value: '["https://luxestay-eosin.vercel.app","https://luxestay.vercel.app"]'
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "60"

databases:
  - name: luxestay-db
    databaseName: luxestay
    user: luxestay
